### ISSUE TITLE
Unsupported value: flutter_mute.SwiftFlutterMutePlugin.RingerMode.Normal of type __SwiftValue

### ISSUE THREAD

**Issue by timcreatedit** [Alezhka/flutter_mute#2]
When running on an iPhone 12 Pro Max Simulator, the app crashes immediately as when trying to access the ringer mode with this message in the console.

On my physical iPhone 8, everything works fine.

**Comment by Alezhka** [comment]
Please check v0.0.3. On simulator always return normal mode.
